development:
  adapter: postgresql
  encoding: unicode
  port: '5432'
  host: 'localhost'
  database: blog-post-development
  pool: 15
  username: postgres
  password: password
  # variables:
  #   statement_timeout: <%= ENV['DATABASE_STATEMENT_TIMEOUT'] || 60 * 1000 %>

test:
  adapter: postgresql
  encoding: unicode
  port: '5432'
  database: blog-post-test
  pool: 25
  host: 'localhost'
  username: postgres
  password: password

# staging:
#   adapter: postgresql
#   encoding: unicode
#   prepared_statements: false
#   url: <%= ENV["DATABASE_URL"] %>
#   pool: <%= ENV['APP_PROC_NAME'].to_s =~ /sidekiq/ ? (ENV["SIDEKIQ_DATABASE_POOL"] || 25) : (ENV['APP_PROC_NAME'].to_s =~ /rpc/ ? (ENV["RPC_DATABASE_POOL"] || 10) : (ENV["DATABASE_POOL"] || 15)) %>
#   variables:
#     statement_timeout: <%= ENV['DATABASE_STATEMENT_TIMEOUT'] || 60 * 1000 %>

# production:
#   adapter: postgresql
#   encoding: unicode
#   prepared_statements: false
#   url: <%= ENV["DATABASE_URL"] %>
#   pool: <%= ENV['APP_PROC_NAME'].to_s =~ /sidekiq/ ? (ENV["SIDEKIQ_DATABASE_POOL"] || 25) : (ENV['APP_PROC_NAME'].to_s =~ /rpc/ ? (ENV["RPC_DATABASE_POOL"] || 10) : (ENV["DATABASE_POOL"] || 15)) %>
#   variables:
#     statement_timeout: <%= ENV['DATABASE_STATEMENT_TIMEOUT'] || 60 * 1000 %>
